// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL6pxn9vuIIS8tXAU6Qg5D0W9LGvIynU0',
    appId: '1:272020107144:web:4dc6ade6716ca74da3d43d',
    messagingSenderId: '272020107144',
    projectId: 'chat-aab0c',
    authDomain: 'chat-aab0c.firebaseapp.com',
    storageBucket: 'chat-aab0c.appspot.com',
    measurementId: 'G-HNX9TM17BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbi1ET3COsGmtJXOSlJNPElvBp-2Y7RO0',
    appId: '1:272020107144:android:4344f7ddb9e849aaa3d43d',
    messagingSenderId: '272020107144',
    projectId: 'chat-aab0c',
    storageBucket: 'chat-aab0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXG2voMgEKN3MCk5B--1WI_rJYaU_OUew',
    appId: '1:272020107144:ios:abcb2e2e58aa9f0ba3d43d',
    messagingSenderId: '272020107144',
    projectId: 'chat-aab0c',
    storageBucket: 'chat-aab0c.appspot.com',
    iosBundleId: 'com.IshanGrover.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXG2voMgEKN3MCk5B--1WI_rJYaU_OUew',
    appId: '1:272020107144:ios:abcb2e2e58aa9f0ba3d43d',
    messagingSenderId: '272020107144',
    projectId: 'chat-aab0c',
    storageBucket: 'chat-aab0c.appspot.com',
    iosBundleId: 'com.IshanGrover.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL6pxn9vuIIS8tXAU6Qg5D0W9LGvIynU0',
    appId: '1:272020107144:web:bf1f3937842fed8ca3d43d',
    messagingSenderId: '272020107144',
    projectId: 'chat-aab0c',
    authDomain: 'chat-aab0c.firebaseapp.com',
    storageBucket: 'chat-aab0c.appspot.com',
    measurementId: 'G-728ZT9NP17',
  );
}
